# Generated by Django 4.1.7 on 2023-03-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('discount_price', models.FloatField()),
                ('category', models.CharField(choices=[('AP', 'Apple'), ('SM', 'Samsung'), ('ON', 'Oneplus'), ('MI', 'Xiaomi'), ('vv', 'Vivo'), ('NO', 'Nokia')], max_length=5)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
